/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/layout'
import { Route as PageRouteImport } from './routes/page'
import { Route as AuthenticatedSettingsLayoutRouteImport } from './routes/_authenticated/settings/layout'
import { Route as AuthenticatedDashboardLayoutRouteImport } from './routes/_authenticated/_dashboard/layout'
import { Route as AuthenticatedSettingsPageRouteImport } from './routes/_authenticated/settings/page'
import { Route as AuthenticatedSettingsTerminalPageRouteImport } from './routes/_authenticated/settings/terminal/page'
import { Route as AuthenticatedSettingsSessionsPageRouteImport } from './routes/_authenticated/settings/sessions/page'
import { Route as AuthenticatedSettingsPresetsPageRouteImport } from './routes/_authenticated/settings/presets/page'
import { Route as AuthenticatedSettingsPreferencesPageRouteImport } from './routes/_authenticated/settings/preferences/page'
import { Route as AuthenticatedSettingsKeyboardPageRouteImport } from './routes/_authenticated/settings/keyboard/page'
import { Route as AuthenticatedSettingsBehaviorPageRouteImport } from './routes/_authenticated/settings/behavior/page'
import { Route as AuthenticatedSettingsAppearancePageRouteImport } from './routes/_authenticated/settings/appearance/page'
import { Route as AuthenticatedDashboardNodesPageRouteImport } from './routes/_authenticated/_dashboard/nodes/page'
import { Route as AuthenticatedDashboardNodePageRouteImport } from './routes/_authenticated/_dashboard/node/page'
import { Route as AuthenticatedSettingsRepositoryRepositoryIdPageRouteImport } from './routes/_authenticated/settings/repository/$repositoryId/page'
import { Route as AuthenticatedSettingsNodeNodeIdPageRouteImport } from './routes/_authenticated/settings/node/$nodeId/page'
import { Route as AuthenticatedDashboardProjectProjectIdPageRouteImport } from './routes/_authenticated/_dashboard/project/$projectId/page'
import { Route as AuthenticatedDashboardNodeNodeIdPageRouteImport } from './routes/_authenticated/_dashboard/node/$nodeId/page'

const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsLayoutRoute =
  AuthenticatedSettingsLayoutRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutRoute =
  AuthenticatedDashboardLayoutRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedSettingsPageRoute =
  AuthenticatedSettingsPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsTerminalPageRoute =
  AuthenticatedSettingsTerminalPageRouteImport.update({
    id: '/terminal/',
    path: '/terminal/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsSessionsPageRoute =
  AuthenticatedSettingsSessionsPageRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsPresetsPageRoute =
  AuthenticatedSettingsPresetsPageRouteImport.update({
    id: '/presets/',
    path: '/presets/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsPreferencesPageRoute =
  AuthenticatedSettingsPreferencesPageRouteImport.update({
    id: '/preferences/',
    path: '/preferences/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsKeyboardPageRoute =
  AuthenticatedSettingsKeyboardPageRouteImport.update({
    id: '/keyboard/',
    path: '/keyboard/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsBehaviorPageRoute =
  AuthenticatedSettingsBehaviorPageRouteImport.update({
    id: '/behavior/',
    path: '/behavior/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsAppearancePageRoute =
  AuthenticatedSettingsAppearancePageRouteImport.update({
    id: '/appearance/',
    path: '/appearance/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedDashboardNodesPageRoute =
  AuthenticatedDashboardNodesPageRouteImport.update({
    id: '/nodes/',
    path: '/nodes/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardNodePageRoute =
  AuthenticatedDashboardNodePageRouteImport.update({
    id: '/node/',
    path: '/node/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedSettingsRepositoryRepositoryIdPageRoute =
  AuthenticatedSettingsRepositoryRepositoryIdPageRouteImport.update({
    id: '/repository/$repositoryId/',
    path: '/repository/$repositoryId/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsNodeNodeIdPageRoute =
  AuthenticatedSettingsNodeNodeIdPageRouteImport.update({
    id: '/node/$nodeId/',
    path: '/node/$nodeId/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedDashboardProjectProjectIdPageRoute =
  AuthenticatedDashboardProjectProjectIdPageRouteImport.update({
    id: '/project/$projectId/',
    path: '/project/$projectId/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardNodeNodeIdPageRoute =
  AuthenticatedDashboardNodeNodeIdPageRouteImport.update({
    id: '/node/$nodeId/',
    path: '/node/$nodeId/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/settings': typeof AuthenticatedSettingsLayoutRouteWithChildren
  '/settings/': typeof AuthenticatedSettingsPageRoute
  '/node/': typeof AuthenticatedDashboardNodePageRoute
  '/nodes/': typeof AuthenticatedDashboardNodesPageRoute
  '/settings/appearance/': typeof AuthenticatedSettingsAppearancePageRoute
  '/settings/behavior/': typeof AuthenticatedSettingsBehaviorPageRoute
  '/settings/keyboard/': typeof AuthenticatedSettingsKeyboardPageRoute
  '/settings/preferences/': typeof AuthenticatedSettingsPreferencesPageRoute
  '/settings/presets/': typeof AuthenticatedSettingsPresetsPageRoute
  '/settings/sessions/': typeof AuthenticatedSettingsSessionsPageRoute
  '/settings/terminal/': typeof AuthenticatedSettingsTerminalPageRoute
  '/node/$nodeId/': typeof AuthenticatedDashboardNodeNodeIdPageRoute
  '/project/$projectId/': typeof AuthenticatedDashboardProjectProjectIdPageRoute
  '/settings/node/$nodeId/': typeof AuthenticatedSettingsNodeNodeIdPageRoute
  '/settings/repository/$repositoryId/': typeof AuthenticatedSettingsRepositoryRepositoryIdPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/settings': typeof AuthenticatedSettingsPageRoute
  '/node': typeof AuthenticatedDashboardNodePageRoute
  '/nodes': typeof AuthenticatedDashboardNodesPageRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearancePageRoute
  '/settings/behavior': typeof AuthenticatedSettingsBehaviorPageRoute
  '/settings/keyboard': typeof AuthenticatedSettingsKeyboardPageRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesPageRoute
  '/settings/presets': typeof AuthenticatedSettingsPresetsPageRoute
  '/settings/sessions': typeof AuthenticatedSettingsSessionsPageRoute
  '/settings/terminal': typeof AuthenticatedSettingsTerminalPageRoute
  '/node/$nodeId': typeof AuthenticatedDashboardNodeNodeIdPageRoute
  '/project/$projectId': typeof AuthenticatedDashboardProjectProjectIdPageRoute
  '/settings/node/$nodeId': typeof AuthenticatedSettingsNodeNodeIdPageRoute
  '/settings/repository/$repositoryId': typeof AuthenticatedSettingsRepositoryRepositoryIdPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/_authenticated': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/_dashboard': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsLayoutRouteWithChildren
  '/_authenticated/settings/': typeof AuthenticatedSettingsPageRoute
  '/_authenticated/_dashboard/node/': typeof AuthenticatedDashboardNodePageRoute
  '/_authenticated/_dashboard/nodes/': typeof AuthenticatedDashboardNodesPageRoute
  '/_authenticated/settings/appearance/': typeof AuthenticatedSettingsAppearancePageRoute
  '/_authenticated/settings/behavior/': typeof AuthenticatedSettingsBehaviorPageRoute
  '/_authenticated/settings/keyboard/': typeof AuthenticatedSettingsKeyboardPageRoute
  '/_authenticated/settings/preferences/': typeof AuthenticatedSettingsPreferencesPageRoute
  '/_authenticated/settings/presets/': typeof AuthenticatedSettingsPresetsPageRoute
  '/_authenticated/settings/sessions/': typeof AuthenticatedSettingsSessionsPageRoute
  '/_authenticated/settings/terminal/': typeof AuthenticatedSettingsTerminalPageRoute
  '/_authenticated/_dashboard/node/$nodeId/': typeof AuthenticatedDashboardNodeNodeIdPageRoute
  '/_authenticated/_dashboard/project/$projectId/': typeof AuthenticatedDashboardProjectProjectIdPageRoute
  '/_authenticated/settings/node/$nodeId/': typeof AuthenticatedSettingsNodeNodeIdPageRoute
  '/_authenticated/settings/repository/$repositoryId/': typeof AuthenticatedSettingsRepositoryRepositoryIdPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/'
    | '/node/'
    | '/nodes/'
    | '/settings/appearance/'
    | '/settings/behavior/'
    | '/settings/keyboard/'
    | '/settings/preferences/'
    | '/settings/presets/'
    | '/settings/sessions/'
    | '/settings/terminal/'
    | '/node/$nodeId/'
    | '/project/$projectId/'
    | '/settings/node/$nodeId/'
    | '/settings/repository/$repositoryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/node'
    | '/nodes'
    | '/settings/appearance'
    | '/settings/behavior'
    | '/settings/keyboard'
    | '/settings/preferences'
    | '/settings/presets'
    | '/settings/sessions'
    | '/settings/terminal'
    | '/node/$nodeId'
    | '/project/$projectId'
    | '/settings/node/$nodeId'
    | '/settings/repository/$repositoryId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/settings/'
    | '/_authenticated/_dashboard/node/'
    | '/_authenticated/_dashboard/nodes/'
    | '/_authenticated/settings/appearance/'
    | '/_authenticated/settings/behavior/'
    | '/_authenticated/settings/keyboard/'
    | '/_authenticated/settings/preferences/'
    | '/_authenticated/settings/presets/'
    | '/_authenticated/settings/sessions/'
    | '/_authenticated/settings/terminal/'
    | '/_authenticated/_dashboard/node/$nodeId/'
    | '/_authenticated/_dashboard/project/$projectId/'
    | '/_authenticated/settings/node/$nodeId/'
    | '/_authenticated/settings/repository/$repositoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_dashboard': {
      id: '/_authenticated/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/terminal/': {
      id: '/_authenticated/settings/terminal/'
      path: '/terminal'
      fullPath: '/settings/terminal/'
      preLoaderRoute: typeof AuthenticatedSettingsTerminalPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/sessions/': {
      id: '/_authenticated/settings/sessions/'
      path: '/sessions'
      fullPath: '/settings/sessions/'
      preLoaderRoute: typeof AuthenticatedSettingsSessionsPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/presets/': {
      id: '/_authenticated/settings/presets/'
      path: '/presets'
      fullPath: '/settings/presets/'
      preLoaderRoute: typeof AuthenticatedSettingsPresetsPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/preferences/': {
      id: '/_authenticated/settings/preferences/'
      path: '/preferences'
      fullPath: '/settings/preferences/'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/keyboard/': {
      id: '/_authenticated/settings/keyboard/'
      path: '/keyboard'
      fullPath: '/settings/keyboard/'
      preLoaderRoute: typeof AuthenticatedSettingsKeyboardPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/behavior/': {
      id: '/_authenticated/settings/behavior/'
      path: '/behavior'
      fullPath: '/settings/behavior/'
      preLoaderRoute: typeof AuthenticatedSettingsBehaviorPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/appearance/': {
      id: '/_authenticated/settings/appearance/'
      path: '/appearance'
      fullPath: '/settings/appearance/'
      preLoaderRoute: typeof AuthenticatedSettingsAppearancePageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/_dashboard/nodes/': {
      id: '/_authenticated/_dashboard/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof AuthenticatedDashboardNodesPageRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard/node/': {
      id: '/_authenticated/_dashboard/node/'
      path: '/node'
      fullPath: '/node/'
      preLoaderRoute: typeof AuthenticatedDashboardNodePageRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/settings/repository/$repositoryId/': {
      id: '/_authenticated/settings/repository/$repositoryId/'
      path: '/repository/$repositoryId'
      fullPath: '/settings/repository/$repositoryId/'
      preLoaderRoute: typeof AuthenticatedSettingsRepositoryRepositoryIdPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/node/$nodeId/': {
      id: '/_authenticated/settings/node/$nodeId/'
      path: '/node/$nodeId'
      fullPath: '/settings/node/$nodeId/'
      preLoaderRoute: typeof AuthenticatedSettingsNodeNodeIdPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/_dashboard/project/$projectId/': {
      id: '/_authenticated/_dashboard/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof AuthenticatedDashboardProjectProjectIdPageRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard/node/$nodeId/': {
      id: '/_authenticated/_dashboard/node/$nodeId/'
      path: '/node/$nodeId'
      fullPath: '/node/$nodeId/'
      preLoaderRoute: typeof AuthenticatedDashboardNodeNodeIdPageRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
  }
}

interface AuthenticatedDashboardLayoutRouteChildren {
  AuthenticatedDashboardNodePageRoute: typeof AuthenticatedDashboardNodePageRoute
  AuthenticatedDashboardNodesPageRoute: typeof AuthenticatedDashboardNodesPageRoute
  AuthenticatedDashboardNodeNodeIdPageRoute: typeof AuthenticatedDashboardNodeNodeIdPageRoute
  AuthenticatedDashboardProjectProjectIdPageRoute: typeof AuthenticatedDashboardProjectProjectIdPageRoute
}

const AuthenticatedDashboardLayoutRouteChildren: AuthenticatedDashboardLayoutRouteChildren =
  {
    AuthenticatedDashboardNodePageRoute: AuthenticatedDashboardNodePageRoute,
    AuthenticatedDashboardNodesPageRoute: AuthenticatedDashboardNodesPageRoute,
    AuthenticatedDashboardNodeNodeIdPageRoute:
      AuthenticatedDashboardNodeNodeIdPageRoute,
    AuthenticatedDashboardProjectProjectIdPageRoute:
      AuthenticatedDashboardProjectProjectIdPageRoute,
  }

const AuthenticatedDashboardLayoutRouteWithChildren =
  AuthenticatedDashboardLayoutRoute._addFileChildren(
    AuthenticatedDashboardLayoutRouteChildren,
  )

interface AuthenticatedSettingsLayoutRouteChildren {
  AuthenticatedSettingsPageRoute: typeof AuthenticatedSettingsPageRoute
  AuthenticatedSettingsAppearancePageRoute: typeof AuthenticatedSettingsAppearancePageRoute
  AuthenticatedSettingsBehaviorPageRoute: typeof AuthenticatedSettingsBehaviorPageRoute
  AuthenticatedSettingsKeyboardPageRoute: typeof AuthenticatedSettingsKeyboardPageRoute
  AuthenticatedSettingsPreferencesPageRoute: typeof AuthenticatedSettingsPreferencesPageRoute
  AuthenticatedSettingsPresetsPageRoute: typeof AuthenticatedSettingsPresetsPageRoute
  AuthenticatedSettingsSessionsPageRoute: typeof AuthenticatedSettingsSessionsPageRoute
  AuthenticatedSettingsTerminalPageRoute: typeof AuthenticatedSettingsTerminalPageRoute
  AuthenticatedSettingsNodeNodeIdPageRoute: typeof AuthenticatedSettingsNodeNodeIdPageRoute
  AuthenticatedSettingsRepositoryRepositoryIdPageRoute: typeof AuthenticatedSettingsRepositoryRepositoryIdPageRoute
}

const AuthenticatedSettingsLayoutRouteChildren: AuthenticatedSettingsLayoutRouteChildren =
  {
    AuthenticatedSettingsPageRoute: AuthenticatedSettingsPageRoute,
    AuthenticatedSettingsAppearancePageRoute:
      AuthenticatedSettingsAppearancePageRoute,
    AuthenticatedSettingsBehaviorPageRoute:
      AuthenticatedSettingsBehaviorPageRoute,
    AuthenticatedSettingsKeyboardPageRoute:
      AuthenticatedSettingsKeyboardPageRoute,
    AuthenticatedSettingsPreferencesPageRoute:
      AuthenticatedSettingsPreferencesPageRoute,
    AuthenticatedSettingsPresetsPageRoute:
      AuthenticatedSettingsPresetsPageRoute,
    AuthenticatedSettingsSessionsPageRoute:
      AuthenticatedSettingsSessionsPageRoute,
    AuthenticatedSettingsTerminalPageRoute:
      AuthenticatedSettingsTerminalPageRoute,
    AuthenticatedSettingsNodeNodeIdPageRoute:
      AuthenticatedSettingsNodeNodeIdPageRoute,
    AuthenticatedSettingsRepositoryRepositoryIdPageRoute:
      AuthenticatedSettingsRepositoryRepositoryIdPageRoute,
  }

const AuthenticatedSettingsLayoutRouteWithChildren =
  AuthenticatedSettingsLayoutRoute._addFileChildren(
    AuthenticatedSettingsLayoutRouteChildren,
  )

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedDashboardLayoutRoute: typeof AuthenticatedDashboardLayoutRouteWithChildren
  AuthenticatedSettingsLayoutRoute: typeof AuthenticatedSettingsLayoutRouteWithChildren
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedDashboardLayoutRoute:
    AuthenticatedDashboardLayoutRouteWithChildren,
  AuthenticatedSettingsLayoutRoute:
    AuthenticatedSettingsLayoutRouteWithChildren,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
